version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      
  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - echo "Creating build directory..."
      - mkdir -p build
      
  build:
    commands:
      - echo "Build phase started on `date`"
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt -t build/
      - echo "Copying source code..."
      - cp -r src build/
      - echo "Copying prompts..."
      - cp -r prompts build/
      - echo "Copying feeds.json..."
      - cp feeds.json build/
      - echo "Build completed on `date`"
      
  post_build:
    commands:
      - echo "Post-build phase started on `date`"
      - ls -lh build/
      - echo "Build successful!"

artifacts:
  files:
    - '**/*'
  base-directory: build
  name: BuildArtifact

cache:
  paths:
    - '/root/.cache/pip/**/*'
